name: Lambda Deploy
description: Deploy an AWS Lambda using Terraform
inputs:
  workspace:
    description: 'Terraform Workspace'
    required: true

  project:
    description: 'Project this Service is part of'
    required: true

  owner:
    description: 'Project owner/team'
    required: true

  email:
    description: 'Project email address'
    required: true

  destroy:
    description: 'Runs Terraform destroy to destroy existing resources created by this action'
    required: false
    default: false

  funcion_name:
    description: 'Lambda function name'
    required: true

  region:
    description: 'AWS region to deploy to'
    required: false
    default: "us-west-2"

  runtime:
    description: 'Programming language to use for the lambda. Valid values: https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime'
    required: true

  zip_payload:
    description: 'Path to the function's deployment package within the local filesystem'
    required: true

  environmental_variables:
    description: 'JSON map of environment variables to configure on the lambda.'
    required: false

  handler:
    description: 'Lambda handler in the format filename.function_name'
    required: true

  memory_size:
    description: 'Amount of memory in MB your Lambda Function can use at runtime'
    required: false
    default: 128

  timeout:
    description: 'The amount of time your Lambda Function has to run in seconds'
    required: false
    default: 3

  policy_arns:
    description: 'A comma separated list of IAM policies ARNs to be attached to the auto-created lambda role'
    required: false

  subnet_ids:
    description: 'A comma separated list of subnet IDs associated with the Lambda function. (Required for vpc_config ONLY)'
    required: false
  security_group_ids:
    description: 'A comma separated list of security group IDs associated with the Lambda function. (Required for vpc_config ONLY)'
    required: false

  enable_cloudwatch_event_trigger:
    description: 'Boolean to configure the lambda to fire based on a cloudwatch rule'
    required: false
    default: false
  cloudwatch_event_name:
    description: 'Name attribute of the cloudwatch event to fire off of'
    required: false
  cloudwatch_event_arn:
    description: 'ARN attribute of the cloudwatch event to fire off of'
    required: false

outputs:
  lambda_name:
    description: 'Name of the created function'
  lambda_arn:
    description: 'ARN of the created function'
  lambda_invoke_arn:
    description: 'The ARN to be used for invoking Lambda Function from API Gateway - to be used in aws_api_gateway_integration's uri'
  lambda_role:
    description: 'IAM role attached to the Lambda Function'
  
runs:
  using: docker
  image: Dockerfile
